import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Heading,
  Hr,
  Link,
  Tailwind,
} from "@react-email/components";
import { getDashboardLocaleCopy } from "@/lib/i18n/dashboardCopy";

interface StrategyMemoProps {
  executiveSummary: string;
  actions: Array<{
    title: string;
    description: string;
    priority: string;
    estimatedROI: string;
  }>;
  businessName?: string;
  generatedAt?: string;
  locale?: string;
}

export const StrategyMemo = ({
  executiveSummary,
  actions,
  businessName = "AuraSales",
  generatedAt = new Date().toLocaleDateString(),
  locale = "en",
}: StrategyMemoProps) => {
  const copy = getDashboardLocaleCopy(locale);
  const memoTitle = copy.pdf.strategyMemoTitle ?? "AURA Strategic Intelligence Memo";
  const analysisLabel = copy.pdf.analysisLabel ?? "Analysis";
  const summaryHeading = copy.pdf.strategySummaryHeading ?? "Executive Summary";
  const actionsHeading = copy.pdf.strategyActionsHeading ?? "Prescriptive Actions (Prioritized)";
  const highLabel = copy.pdf.priorityHigh ?? "High";
  const mediumLabel = copy.pdf.priorityMedium ?? "Medium";
  const lowLabel = copy.pdf.priorityLow ?? "Low";
  const estimatedRoiLabel = copy.pdf.estimatedROI ?? "Estimated ROI";
  const readyLabel = copy.pdf.readyToExecute ?? "Ready to execute?";
  const openDashboardLabel = copy.pdf.openDashboard ?? "Open Dashboard";
  const footerNote =
    copy.pdf.strategyFooterNote ??
    "This report was autonomously generated by AURA AI based on your sales performance data. All insights are data-driven and confidential.";

  return (
    <Html>
      <Head />
      <Tailwind>
        <Body className="bg-slate-50 font-sans p-4">
          <Container className="bg-white border border-slate-200 rounded-lg p-8 shadow-sm max-w-2xl">
            <div className="border-b border-slate-200 pb-4">
              <Heading className="text-2xl font-bold text-slate-900 m-0">
                {memoTitle}
              </Heading>
              <Text className="text-slate-500 text-sm mt-2 italic m-0">
                {copy.pdf.confidential} {analysisLabel} - {businessName} - {generatedAt}
              </Text>
            </div>

            <Section className="mt-6">
              <Heading as="h2" className="text-lg font-semibold text-slate-800 mb-2">
                {summaryHeading}
              </Heading>
              <Text className="text-slate-700 leading-relaxed m-0">
                {executiveSummary}
              </Text>
            </Section>

            <Hr className="my-6 border-slate-200" />

            <Section>
              <Heading as="h2" className="text-lg font-semibold text-slate-800 mb-3">
                {actionsHeading}
              </Heading>

              <div className="space-y-4">
                {actions.map((action, i) => (
                  <div
                    key={i}
                    className="border-l-4 border-blue-500 pl-4 py-3 bg-blue-50 rounded-r"
                  >
                    <div className="flex items-start justify-between mb-1">
                      <Heading as="h3" className="text-base font-bold text-slate-900 m-0">
                        {i + 1}. {action.title}
                      </Heading>
                      <span
                        className={`text-xs font-semibold px-2 py-1 rounded ${
                          action.priority === "high"
                            ? "bg-red-100 text-red-700"
                            : action.priority === "medium"
                              ? "bg-amber-100 text-amber-700"
                              : "bg-green-100 text-green-700"
                        }`}
                      >
                        {action.priority === "high"
                          ? highLabel
                          : action.priority === "medium"
                            ? mediumLabel
                            : lowLabel}
                      </span>
                    </div>

                    <Text className="text-slate-700 text-sm leading-relaxed m-0 mb-2">
                      {action.description}
                    </Text>

                    <Text className="text-slate-600 text-xs font-semibold m-0">
                      {estimatedRoiLabel}: {action.estimatedROI}
                    </Text>
                  </div>
                ))}
              </div>
            </Section>

            <Section className="mt-8 p-4 bg-blue-50 border border-blue-200 rounded-lg">
              <Text className="text-slate-800 text-sm m-0 mb-3">
                <strong>{readyLabel}</strong> {copy.pdf.strategySummaryTail ?? readyLabel}
              </Text>
              <Link
                href="https://aurasales.app/dashboard"
                className="inline-block bg-blue-600 text-white px-4 py-2 rounded font-semibold text-sm text-center no-underline"
              >
                {openDashboardLabel}
              </Link>
            </Section>

            <Hr className="my-6 border-slate-200" />
            <Text className="text-xs text-slate-400 text-center m-0">
              {footerNote}
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
};
