-- Create comments table for war room discussions
CREATE TABLE IF NOT EXISTS comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  user_id UUID NOT NULL,
  text TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  parent_id UUID REFERENCES comments(id) ON DELETE CASCADE, -- For threading
  chart_context TEXT, -- e.g., "revenue-forecast", "sentiment-breakdown", "abuja-branch"
  is_internal_only BOOLEAN DEFAULT FALSE, -- If TRUE, Aura AI doesn't see it
  is_ai_response BOOLEAN DEFAULT FALSE, -- If TRUE, this was generated by Aura AI
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_comments_company_id ON comments(company_id);
CREATE INDEX idx_comments_user_id ON comments(user_id);
CREATE INDEX idx_comments_chart_context ON comments(chart_context);
CREATE INDEX idx_comments_parent_id ON comments(parent_id);
CREATE INDEX idx_comments_timestamp ON comments(timestamp DESC);
CREATE INDEX idx_comments_thread ON comments(parent_id, timestamp);

-- Create comment_mentions table to track @mentions
CREATE TABLE IF NOT EXISTS comment_mentions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  comment_id UUID NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  mentioned_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  is_aura_mention BOOLEAN DEFAULT FALSE, -- TRUE if mentioning @Aura AI
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_comment_mentions_comment_id ON comment_mentions(comment_id);
CREATE INDEX idx_comment_mentions_user_id ON comment_mentions(mentioned_user_id);
CREATE INDEX idx_comment_mentions_aura ON comment_mentions(is_aura_mention);

-- Create comment_reactions table for likes/reactions
CREATE TABLE IF NOT EXISTS comment_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  comment_id UUID NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reaction_type TEXT DEFAULT 'like', -- 'like', 'insightful', 'helpful', etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(comment_id, user_id, reaction_type)
);

CREATE INDEX idx_comment_reactions_comment_id ON comment_reactions(comment_id);
CREATE INDEX idx_comment_reactions_user_id ON comment_reactions(user_id);

-- Row Level Security (RLS) Policies
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_reactions ENABLE ROW LEVEL SECURITY;

-- Users can only see comments from their company
CREATE POLICY "Users can view company comments"
  ON comments FOR SELECT
  USING (company_id = (SELECT company_id FROM auth.users WHERE id = auth.uid()));

-- Users can only insert comments for their company
CREATE POLICY "Users can create comments in their company"
  ON comments FOR INSERT
  WITH CHECK (company_id = (SELECT company_id FROM auth.users WHERE id = auth.uid()) AND user_id = auth.uid());

-- Users can only update their own comments
CREATE POLICY "Users can update own comments"
  ON comments FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can only delete their own comments
CREATE POLICY "Users can delete own comments"
  ON comments FOR DELETE
  USING (user_id = auth.uid());

-- Similar policies for mentions and reactions
CREATE POLICY "Users can view comment mentions"
  ON comment_mentions FOR SELECT
  USING (comment_id IN (SELECT id FROM comments WHERE company_id = (SELECT company_id FROM auth.users WHERE id = auth.uid())));

CREATE POLICY "Users can create comment mentions"
  ON comment_mentions FOR INSERT
  WITH CHECK (comment_id IN (SELECT id FROM comments WHERE company_id = (SELECT company_id FROM auth.users WHERE id = auth.uid())));

-- Grant access
GRANT SELECT, INSERT, UPDATE, DELETE ON comments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON comment_mentions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON comment_reactions TO authenticated;
