/**
 * Market Insights Dashboard Component
 * 
 * Displays market data correlations, recommendations, and auto-generated tasks.
 * Shows live data status with fallback messaging.
 */

'use client';

import React, { useCallback, useEffect, useState } from 'react';
import {
  AlertCircle,
  TrendingDown,
  TrendingUp,
  Zap,
  CheckCircle2,
  AlertTriangle,
} from 'lucide-react';
import MarketDataStatusComponent, {
  useMarketDataStatus,
} from './MarketDataStatus';
import { useTranslatedTexts } from '@/hooks/useTranslatedTexts';

interface Correlation {
  id: string;
  type: string;
  marketFactor: string;
  internalImpact: string;
  confidence: number;
  direction: 'positive' | 'negative' | 'neutral';
  description: string;
}

interface Recommendation {
  id: string;
  title: string;
  description: string;
  actionItems: string[];
  estimatedImpact: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  relatedCorrelations: string[];
}

interface AutoTask {
  id: string;
  title: string;
  description: string;
  category: string;
  dueDate: string;
  assigneeSuggestion?: string;
  estimatedEffort: 'small' | 'medium' | 'large';
  linkedCorrelations: string[];
}

interface MarketAnalysis {
  ticker: string;
  timestamp: string;
  correlations: Correlation[];
  recommendations: Recommendation[];
  autoGeneratedTasks: AutoTask[];
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  summaryText: string;
  dataSource: string[];
  demoMode?: boolean;
}

interface MarketInsightsDashboardProps {
  ticker?: string;
  showTasks?: boolean;
  showRecommendations?: boolean;
  autoRefreshMinutes?: number;
  targetLanguage?: string;
  hasUploadedData?: boolean;
  csvContent?: string;
}

export const MarketInsightsDashboard: React.FC<MarketInsightsDashboardProps> = ({
  ticker = 'NGSE:MTNN',
  showTasks = true,
  showRecommendations = true,
  autoRefreshMinutes = 60,
  targetLanguage = 'en',
  hasUploadedData = false,
  csvContent = '',
}) => {
  const [analysis, setAnalysis] = useState<MarketAnalysis | null>(null);
  const [translatedAnalysis, setTranslatedAnalysis] = useState<MarketAnalysis | null>(null);
  const [loading, setLoading] = useState(true);
  const [isTranslating, setIsTranslating] = useState(false);
  const { status, refetch: refetchStatus } = useMarketDataStatus(ticker);
  const isDemoAnalysis =
    !hasUploadedData &&
    (!!analysis?.demoMode ||
      (analysis?.dataSource || []).some((src) => String(src).includes('mock')));
  const displayStatus = hasUploadedData ? { ...status, demoMode: false } : status;

  const fetchAnalysis = useCallback(async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/analyze/market-correlation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ticker,
          includeSalesData: true,
          csvContent,
        }),
      });
      const responseText = await response.text();
      let data: {
        success?: boolean;
        analysis?: MarketAnalysis;
      } | null = null;

      try {
        data = JSON.parse(responseText) as {
          success?: boolean;
          analysis?: MarketAnalysis;
        };
      } catch {
        console.warn('Market analysis API returned a non-JSON response');
      }

      if (data?.success && data.analysis) {
        const dataSource = data.analysis.dataSource || [];
        const demoMode =
          Boolean(data.analysis.demoMode) ||
          dataSource.some((src: string) => String(src).includes('mock'));
        setAnalysis({
          ...data.analysis,
          demoMode,
        });
      } else {
        setAnalysis(createDemoAnalysis(ticker));
      }
    } catch (error) {
      console.error('Error fetching analysis:', error);
      setAnalysis(createDemoAnalysis(ticker));
    } finally {
      setLoading(false);
    }
  }, [ticker, csvContent]);

  useEffect(() => {
    fetchAnalysis();

    // Auto-refresh
    if (autoRefreshMinutes > 0) {
      const interval = setInterval(
        () => fetchAnalysis(),
        autoRefreshMinutes * 60 * 1000
      );
      return () => clearInterval(interval);
    }
  }, [fetchAnalysis, autoRefreshMinutes]);

  useEffect(() => {
    let cancelled = false;

    const translateAnalysis = async () => {
      if (!analysis || targetLanguage === 'en') {
        setTranslatedAnalysis(null);
        return;
      }

      const texts: string[] = [
        analysis.summaryText,
        ...analysis.correlations.flatMap((corr) => [
          corr.marketFactor,
          corr.description,
          corr.internalImpact,
        ]),
        ...analysis.recommendations.flatMap((rec) => [
          rec.title,
          rec.description,
          ...rec.actionItems,
          rec.estimatedImpact,
        ]),
        ...analysis.autoGeneratedTasks.flatMap((task) => [
          task.title,
          task.description,
          task.category,
          task.assigneeSuggestion || '',
        ]),
      ].filter((item) => String(item || '').trim().length > 0);

      if (!texts.length) {
        setTranslatedAnalysis(null);
        return;
      }

      try {
        setIsTranslating(true);
        const response = await fetch('/api/translate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            targetLanguage:
              targetLanguage === 'fr'
                ? 'French'
                : targetLanguage === 'es'
                  ? 'Spanish'
                  : targetLanguage === 'de'
                    ? 'German'
                    : targetLanguage === 'ar'
                      ? 'Arabic'
                      : targetLanguage === 'zh'
                        ? 'Chinese (Simplified)'
                        : targetLanguage === 'pt'
                          ? 'Portuguese'
                          : targetLanguage === 'hi'
                            ? 'Hindi'
                            : 'English',
            texts,
          }),
        });
        const payload = await response.json().catch(() => ({}));
        const translated = Array.isArray(payload?.translations) ? payload.translations : texts;
        if (cancelled) return;

        let cursor = 0;
        const nextSummaryText = translated[cursor++] || analysis.summaryText;

        const nextCorrelations = analysis.correlations.map((corr) => {
          const marketFactor = translated[cursor++] || corr.marketFactor;
          const description = translated[cursor++] || corr.description;
          const internalImpact = translated[cursor++] || corr.internalImpact;
          return { ...corr, marketFactor, description, internalImpact };
        });

        const nextRecommendations = analysis.recommendations.map((rec) => {
          const title = translated[cursor++] || rec.title;
          const description = translated[cursor++] || rec.description;
          const actionItems = rec.actionItems.map((item) => translated[cursor++] || item);
          const estimatedImpact = translated[cursor++] || rec.estimatedImpact;
          return { ...rec, title, description, actionItems, estimatedImpact };
        });

        const nextTasks = analysis.autoGeneratedTasks.map((task) => {
          const title = translated[cursor++] || task.title;
          const description = translated[cursor++] || task.description;
          const category = translated[cursor++] || task.category;
          const assigneeSuggestion = task.assigneeSuggestion
            ? translated[cursor++] || task.assigneeSuggestion
            : undefined;
          return { ...task, title, description, category, assigneeSuggestion };
        });

        setTranslatedAnalysis({
          ...analysis,
          summaryText: nextSummaryText,
          correlations: nextCorrelations,
          recommendations: nextRecommendations,
          autoGeneratedTasks: nextTasks,
        });
      } catch {
        if (!cancelled) setTranslatedAnalysis(null);
      } finally {
        if (!cancelled) setIsTranslating(false);
      }
    };

    translateAnalysis();
    return () => {
      cancelled = true;
    };
  }, [analysis, targetLanguage]);

  const [
    translatedDemoMode,
    translatedNoCorrelations,
    translatedNoCorrelationsBody,
    translatedUnable,
    translatedUnableBody,
    translatedRisk,
    translatedMarketFound,
    translatedStrategicRecommendations,
    translatedActionItems,
    translatedEstimatedImpact,
    translatedAutoTasks,
    translatedDue,
    translatedEffort,
    translatedSuggested,
    translatedConfidence,
    translatedImpact,
    translatedPartialLive,
    translatedLiveOffline,
    translatedUsingCached,
    translatedDemoEnabled,
    translatedDemoBody,
    translatedPartialBody,
    translatedOfflineBody,
    translatedCachedBody,
    translatedRetry,
    translatedRetrying,
    translatedLastAttempt,
    translatedLiveFor,
    translatedNoLiveData,
    translatedFallbackBody,
    translatedRefreshData,
  ] = useTranslatedTexts(targetLanguage, [
    'Demo Mode',
    'No Market Correlations Found',
    'Market data is normal with no significant impacts detected for your business.',
    'Unable to Load Analysis',
    'Market analysis could not be generated. Please try again later.',
    'Risk Level:',
    'Market Correlations Found',
    'Strategic Recommendations',
    'Action Items:',
    'Estimated Impact:',
    'Auto-Generated Tasks',
    'Due:',
    'Effort:',
    'Suggested:',
    'confidence',
    'Impact:',
    'Partial Live Data',
    'Live Data Offline',
    'Using Cached Market Data',
    'Demo Data Enabled',
    'Live APIs are unavailable or invalid. Showing sample market/news data.',
    'Some providers are unavailable, but live data is still being served from available sources.',
    'Unable to fetch live market data:',
    'Real-time data ingestion is currently unavailable. Showing cached data from',
    'Retry',
    'Retrying...',
    'Last attempt:',
    'Live market data for',
    'No Live Data Available',
    'Market data ingestion is temporarily offline. Please check your API configuration or try again later.',
    'Refresh Data',
  ]);

  const t = (key: string) =>
    ({
      'Demo Mode': translatedDemoMode,
      'No Market Correlations Found': translatedNoCorrelations,
      'Market data is normal with no significant impacts detected for your business.': translatedNoCorrelationsBody,
      'Unable to Load Analysis': translatedUnable,
      'Market analysis could not be generated. Please try again later.': translatedUnableBody,
      'Risk Level:': translatedRisk,
      'Market Correlations Found': translatedMarketFound,
      'Strategic Recommendations': translatedStrategicRecommendations,
      'Action Items:': translatedActionItems,
      'Estimated Impact:': translatedEstimatedImpact,
      'Auto-Generated Tasks': translatedAutoTasks,
      'Due:': translatedDue,
      'Effort:': translatedEffort,
      'Suggested:': translatedSuggested,
      confidence: translatedConfidence,
      'Impact:': translatedImpact,
      'Partial Live Data': translatedPartialLive,
      'Live Data Offline': translatedLiveOffline,
      'Using Cached Market Data': translatedUsingCached,
      'Demo Data Enabled': translatedDemoEnabled,
      'Live APIs are unavailable or invalid. Showing sample market/news data.': translatedDemoBody,
      'Some providers are unavailable, but live data is still being served from available sources.': translatedPartialBody,
      'Unable to fetch live market data:': translatedOfflineBody,
      'Real-time data ingestion is currently unavailable. Showing cached data from': translatedCachedBody,
      Retry: translatedRetry,
      'Retrying...': translatedRetrying,
      'Last attempt:': translatedLastAttempt,
      'Live market data for': translatedLiveFor,
      'No Live Data Available': translatedNoLiveData,
      'Market data ingestion is temporarily offline. Please check your API configuration or try again later.': translatedFallbackBody,
      'Refresh Data': translatedRefreshData,
    } as Record<string, string>)[key] || key;

  const displayAnalysis = translatedAnalysis || analysis;

  const handleRetry = async () => {
    await refetchStatus();
    await fetchAnalysis();
  };

  return (
    <div className="space-y-6" data-aura-translate-skip>
      {/* Status Component */}
      <MarketDataStatusComponent
        ticker={ticker}
        status={displayStatus}
        onRetry={handleRetry}
        targetLanguage={targetLanguage}
      />

      {/* Loading State */}
      {loading && (
        <div className="flex justify-center items-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        </div>
      )}

      {/* Analysis Content */}
      {!loading && displayAnalysis && (
        <>
          {isDemoAnalysis && (
            <div className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-indigo-100 text-indigo-700 border border-indigo-200">
              {t('Demo Mode')}
            </div>
          )}

          {/* Summary */}
          <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
            <p className="text-sm text-blue-900">{displayAnalysis.summaryText}</p>
          </div>
          {isTranslating && <p className="text-xs text-blue-300">Translating market content...</p>}

          {/* Risk Level Badge */}
          <RiskLevelBadge level={displayAnalysis.riskLevel} t={t} />

          {/* Correlations Section */}
          {displayAnalysis.correlations && displayAnalysis.correlations.length > 0 && (
            <CorrelationsSection correlations={displayAnalysis.correlations} t={t} />
          )}

          {/* Recommendations Section */}
          {showRecommendations &&
            displayAnalysis.recommendations &&
            displayAnalysis.recommendations.length > 0 && (
              <RecommendationsSection
                recommendations={displayAnalysis.recommendations}
                t={t}
              />
            )}

          {/* Auto-Generated Tasks Section */}
          {showTasks &&
            displayAnalysis.autoGeneratedTasks &&
            displayAnalysis.autoGeneratedTasks.length > 0 && (
              <AutoTasksSection tasks={displayAnalysis.autoGeneratedTasks} t={t} />
            )}

          {/* No Insights Message */}
          {!displayAnalysis.correlations ||
            (displayAnalysis.correlations.length === 0 && (
              <div className="rounded-lg border border-gray-200 bg-gray-50 p-6 text-center">
                <AlertCircle className="h-8 w-8 text-gray-400 mx-auto mb-3" />
                <h4 className="text-sm font-medium text-gray-900">
                  {t('No Market Correlations Found')}
                </h4>
                <p className="text-xs text-gray-600 mt-1">
                  {t('Market data is normal with no significant impacts detected for your business.')}
                </p>
              </div>
            ))}
        </>
      )}

      {/* Error State */}
      {!loading && !analysis && (
        <div className="rounded-lg border border-red-200 bg-red-50 p-6 flex gap-3">
          <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-medium text-red-900">
              {t('Unable to Load Analysis')}
            </h4>
            <p className="text-sm text-red-800 mt-1">
              {t('Market analysis could not be generated. Please try again later.')}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

/**
 * Risk Level Badge Component
 */
const RiskLevelBadge: React.FC<{ level: string; t: (key: string) => string }> = ({ level, t }) => {
  const riskStyles = {
    low: 'bg-green-100 text-green-800 border-green-300',
    medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    high: 'bg-orange-100 text-orange-800 border-orange-300',
    critical: 'bg-red-100 text-red-800 border-red-300',
  };

  return (
    <div className={`rounded-lg border p-4 ${riskStyles[level as keyof typeof riskStyles] || ''}`}>
      <div className="flex items-center gap-2">
        {level === 'critical' || level === 'high' ? (
          <AlertTriangle className="h-5 w-5" />
        ) : (
          <CheckCircle2 className="h-5 w-5" />
        )}
        <span className="font-medium capitalize">
          {t('Risk Level:')} {level}
        </span>
      </div>
    </div>
  );
};

/**
 * Correlations Section
 */
const CorrelationsSection: React.FC<{ correlations: Correlation[]; t: (key: string) => string }> = ({
  correlations,
  t,
}) => {
  return (
    <div className="rounded-lg border border-gray-200 p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
        <Zap className="h-5 w-5" />
        {correlations.length} {t('Market Correlations Found')}
      </h3>

      <div className="space-y-3">
        {correlations.map((corr) => (
          <div
            key={corr.id}
            className="border border-gray-200 rounded-lg p-3 bg-gray-50"
          >
            <div className="flex items-start gap-3">
              {corr.direction === 'negative' ? (
                <TrendingDown className="h-4 w-4 text-red-600 flex-shrink-0 mt-0.5" />
              ) : (
                <TrendingUp className="h-4 w-4 text-green-600 flex-shrink-0 mt-0.5" />
              )}

              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium text-gray-900">
                    {corr.marketFactor}
                  </p>
                  <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded">
                    {corr.confidence}% {t('confidence')}
                  </span>
                </div>
                <p className="text-xs text-gray-600 mt-1">{corr.description}</p>
                <p className="text-xs font-medium text-gray-700 mt-2">
                  {t('Impact:')} {corr.internalImpact}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

/**
 * Recommendations Section
 */
const RecommendationsSection: React.FC<{
  recommendations: Recommendation[];
  t: (key: string) => string;
}> =
  ({ recommendations, t }) => {
    return (
      <div className="rounded-lg border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">
          {t('Strategic Recommendations')}
        </h3>

        <div className="space-y-4">
          {recommendations.map((rec) => (
            <div
              key={rec.id}
              className="border border-gray-200 rounded-lg p-4 bg-white"
            >
              <div className="flex items-start justify-between mb-2">
                <h4 className="font-medium text-gray-900">{rec.title}</h4>
                <PriorityBadge priority={rec.priority} />
              </div>

              <p className="text-sm text-gray-600 mb-3">{rec.description}</p>

              <div>
                <p className="text-xs font-semibold text-gray-700 mb-2">
                  {t('Action Items:')}
                </p>
                <ul className="text-xs text-gray-600 space-y-1 ml-4">
                  {rec.actionItems.map((item, idx) => (
                    <li key={idx} className="list-disc">
                      {item}
                    </li>
                  ))}
                </ul>
              </div>

              <p className="text-xs text-green-700 mt-3 font-medium">
                {t('Estimated Impact:')} {rec.estimatedImpact}
              </p>
            </div>
          ))}
        </div>
      </div>
    );
  };

/**
 * Auto Tasks Section
 */
const AutoTasksSection: React.FC<{ tasks: AutoTask[]; t: (key: string) => string }> = ({ tasks, t }) => {
  return (
    <div className="rounded-lg border border-gray-200 p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-4">
        {t('Auto-Generated Tasks')} ({tasks.length})
      </h3>

      <div className="space-y-3">
        {tasks.map((task) => (
          <div
            key={task.id}
            className="border border-gray-200 rounded-lg p-4 bg-white hover:shadow-sm transition"
          >
            <div className="flex items-start justify-between mb-2">
              <h4 className="font-medium text-gray-900">{task.title}</h4>
              <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded">
                {task.category}
              </span>
            </div>

            <p className="text-sm text-gray-600 mb-3">{task.description}</p>

            <div className="flex items-center justify-between text-xs text-gray-600">
              <span>
                {t('Due:')}{' '}
                {new Date(task.dueDate).toLocaleDateString()}
              </span>
              <span className="bg-gray-100 px-2 py-1 rounded">
                {t('Effort:')} {task.estimatedEffort}
              </span>
            </div>

            {task.assigneeSuggestion && (
              <p className="text-xs text-gray-500 mt-2">
                {t('Suggested:')} {task.assigneeSuggestion}
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

/**
 * Priority Badge Component
 */
const PriorityBadge: React.FC<{ priority: string }> = ({ priority }) => {
  const styles = {
    low: 'bg-blue-100 text-blue-800',
    medium: 'bg-yellow-100 text-yellow-800',
    high: 'bg-orange-100 text-orange-800',
    critical: 'bg-red-100 text-red-800',
  };

  return (
    <span
      className={`text-xs font-medium px-2 py-1 rounded capitalize ${
        styles[priority as keyof typeof styles] || ''
      }`}
    >
      {priority}
    </span>
  );
};

export default MarketInsightsDashboard;

function createDemoAnalysis(ticker: string): MarketAnalysis {
  return {
    ticker,
    timestamp: new Date().toISOString(),
    correlations: [
      {
        id: 'demo-corr-1',
        type: 'demand',
        marketFactor: 'Sample market demand signal',
        internalImpact: 'Potential opportunity in tracked sectors',
        confidence: 62,
        direction: 'positive',
        description:
          'Demo insight generated because live market/news APIs are unavailable.',
      },
    ],
    recommendations: [
      {
        id: 'demo-rec-1',
        title: 'Validate API keys',
        description:
          'Connect valid market/news API keys to switch from sample insights to live intelligence.',
        actionItems: [
          'Set ALPHA_VANTAGE_KEY',
          'Set FMP_API_KEY',
          'Set NEWS_API_KEY',
        ],
        estimatedImpact: 'Restore real-time market and headline analysis',
        priority: 'high',
        relatedCorrelations: ['demo-corr-1'],
      },
    ],
    autoGeneratedTasks: [],
    riskLevel: 'medium',
    summaryText:
      'Demo Mode is active. Showing sample market and news insights until valid API credentials are configured.',
    dataSource: ['mock'],
    demoMode: true,
  };
}


