/**
 * Types for the Commenting System with @Aura AI Integration
 */

export interface Comment {
  id: string;
  company_id: string;
  user_id: string;
  text: string;
  timestamp: string;
  parent_id: string | null; // NULL if top-level, otherwise ID of parent comment
  chart_context: string | null; // "revenue-forecast", "sentiment-breakdown", "branch-xyz", etc.
  is_internal_only: boolean; // If TRUE, Aura AI doesn't see it
  is_ai_response: boolean; // If TRUE, generated by Aura AI
  likes_count: number;
  created_at: string;
  updated_at: string;

  // Populated fields (not in DB)
  author?: User;
  mentions?: CommentMention[];
  replies?: Comment[]; // Child comments
  reactions?: CommentReaction[];
}

export interface CommentMention {
  id: string;
  comment_id: string;
  mentioned_user_id: string | null;
  is_aura_mention: boolean;
  created_at: string;

  // Populated fields
  user?: User; // If mentioned_user_id is not null
}

export interface CommentReaction {
  id: string;
  comment_id: string;
  user_id: string;
  reaction_type: 'like' | 'insightful' | 'helpful' | 'question';
  created_at: string;

  // Populated fields
  user?: User;
}

export interface User {
  id: string;
  email: string;
  full_name: string;
  avatar_url?: string;
  is_admin?: boolean;
}

export interface CommentThread {
  id: string;
  root_comment: Comment;
  replies: Comment[];
  total_replies: number;
  last_reply_at: string;
}

export interface ChatCollaborationRequest {
  comment_text: string;
  chart_context: string;
  chart_data?: Record<string, any>;
  user_name: string;
  previous_messages?: Array<{ role: 'user' | 'assistant'; content: string }>;
}

export interface AuraAnalystResponse {
  response: string;
  context_used: string[];
  confidence_score?: number;
  data_summary?: string;
}

export interface MentionSuggestion {
  id: string;
  type: 'user' | 'ai';
  name: string;
  avatar_url?: string;
  email?: string;
  is_aura: boolean;
}

export interface CommentCreateRequest {
  text: string;
  parent_id?: string; // Optional, for replies
  chart_context?: string;
  is_internal_only?: boolean;
  mentions?: string[]; // Array of user IDs and "aura" for AI
}

export interface CommentThread {
  id: string;
  root_comment: Comment;
  reply_count: number;
  has_ai_response: boolean;
  last_activity: string;
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

// Enums
export enum ChartContextType {
  REVENUE_FORECAST = 'revenue-forecast',
  SENTIMENT_BREAKDOWN = 'sentiment-breakdown',
  REGIONAL_INSIGHTS = 'regional-insights',
  SALES_CATEGORY = 'sales-category',
  WHAT_IF_SIMULATOR = 'what-if-simulator',
  AURA_ASSISTANT = 'aura-assistant',
  BRANCH_PERFORMANCE = 'branch-performance',
  PRODUCT_ANALYSIS = 'product-analysis',
  CUSTOM = 'custom',
}

export enum ReactionType {
  LIKE = 'like',
  INSIGHTFUL = 'insightful',
  HELPFUL = 'helpful',
  QUESTION = 'question',
}
