/**
 * Data Correlation Engine Service
 * 
 * Compares internal sales data against market news and trends.
 * Generates automated recommendations and tasks based on correlations.
 * 
 * Example: If market news says "Fuel prices rising" and sales data shows
 * "Delivery costs up", auto-generates a task to "Audit Logistics Providers"
 */

import { MarketDataPayload } from './types';

type NewsArticle = {
  title: string;
  description?: string;
};

type PricePoint = {
  close: number;
};

export interface SalesDataSnapshot {
  period: string; // e.g., "Q4 2025", "Jan 2026"
  totalSales: number;
  costOfGoods: number;
  deliveryCosts: number;
  deliveryCostPercentage: number;
  costTrend: 'increasing' | 'decreasing' | 'stable';
  urgencyIndicators: string[];
}

export interface CorrelationAnalysis {
  ticker: string;
  timestamp: string;
  correlations: Correlation[];
  recommendations: Recommendation[];
  autoGeneratedTasks: AutoTask[];
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  summaryText: string;
}

export interface Correlation {
  id: string;
  type: 'cost' | 'revenue' | 'demand' | 'supply' | 'operational';
  marketFactor: string; // e.g., "Fuel prices"
  internalImpact: string; // e.g., "Delivery costs up 12%"
  confidence: number; // 0-100
  direction: 'positive' | 'negative' | 'neutral';
  description: string;
}

export interface Recommendation {
  id: string;
  title: string;
  description: string;
  actionItems: string[];
  estimatedImpact: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  relatedCorrelations: string[];
}

export interface AutoTask {
  id: string;
  title: string;
  description: string;
  category: 'audit' | 'negotiation' | 'optimization' | 'monitoring' | 'strategic';
  dueDate: string;
  assigneeSuggestion?: string;
  estimatedEffort: 'small' | 'medium' | 'large';
  linkedCorrelations: string[];
}

export class DataCorrelationEngine {
  /**
   * Analyze correlations between market data and sales data
   */
  static async analyzeCorrelations(
    marketData: MarketDataPayload,
    salesData?: SalesDataSnapshot
  ): Promise<CorrelationAnalysis> {
    const correlations = this.findCorrelations(marketData, salesData);
    const recommendations = this.generateRecommendations(correlations);
    const autoTasks = this.generateAutoTasks(correlations);
    const riskLevel = this.assessRiskLevel(correlations);

    return {
      ticker: marketData.ticker,
      timestamp: new Date().toISOString(),
      correlations,
      recommendations,
      autoGeneratedTasks: autoTasks,
      riskLevel,
      summaryText: this.generateSummary(correlations, recommendations, riskLevel),
    };
  }

  /**
   * Find correlations between market trends and internal data
   */
  private static findCorrelations(
    marketData: MarketDataPayload,
    salesData?: SalesDataSnapshot
  ): Correlation[] {
    const correlations: Correlation[] = [];
    let corrId = 0;

    // Analyze news for market trends
    if (marketData.news && marketData.news.length > 0) {
      marketData.news.forEach((article) => {
        const analysis = this.analyzeNewsArticle(article);
        if (analysis) {
          correlations.push({
            ...analysis,
            id: `corr-${++corrId}`,
          });
        }
      });
    }

    // Analyze price trends
    if (marketData.prices && marketData.prices.length > 0) {
      const priceAnalysis = this.analyzePriceTrends(marketData.prices);
      correlations.push(...priceAnalysis.map((a) => ({ ...a, id: `corr-${++corrId}` })));
    }

    if (salesData) {
      const salesAnalysis = this.analyzeSalesSnapshot(salesData);
      if (salesAnalysis) {
        correlations.push({
          ...salesAnalysis,
          id: `corr-${++corrId}`,
        });
      }
    }

    return correlations;
  }

  /**
   * Analyze a single news article for business impact
   */
  private static analyzeNewsArticle(
    article: NewsArticle
  ): Correlation | null {
    const title = article.title.toLowerCase();
    const desc = (article.description || '').toLowerCase();
    const content = `${title} ${desc}`;

    // Define keyword patterns for different business impacts
    const patterns = {
      fuel: {
        keywords: ['fuel', 'oil', 'gas', 'energy', 'commodity'],
        impact: 'Fuel/Energy costs may change - affects logistics',
        type: 'cost' as const,
      },
      supply: {
        keywords: ['supply', 'shortage', 'supply chain', 'disruption', 'logistics'],
        impact: 'Supply chain disruptions - affects operations',
        type: 'supply' as const,
      },
      demand: {
        keywords: ['demand', 'consumer', 'sales', 'market demand', 'consumer spending'],
        impact: 'Market demand trends - affects revenue projections',
        type: 'demand' as const,
      },
      regulation: {
        keywords: ['regulation', 'policy', 'law', 'compliance', 'tax'],
        impact: 'Regulatory changes - affects operational costs',
        type: 'operational' as const,
      },
      economicGrowth: {
        keywords: ['economy', 'gdp', 'growth', 'inflation', 'interest rate'],
        impact: 'Economic conditions shifting - affects overall performance',
        type: 'revenue' as const,
      },
    };

    // Check for pattern matches
    for (const pattern of Object.values(patterns)) {
      const hasMatch = pattern.keywords.some((kw) => content.includes(kw));

      if (hasMatch) {
        let direction: 'positive' | 'negative' | 'neutral' = 'neutral';
        const negativeWords = ['falling', 'down', 'decline', 'crisis', 'problem', 'issue'];
        const positiveWords = ['rising', 'up', 'growth', 'improvement', 'positive'];

        if (negativeWords.some((word) => content.includes(word))) {
          direction = 'negative';
        } else if (positiveWords.some((word) => content.includes(word))) {
          direction = 'positive';
        }

        return {
          id: '', // Will be assigned by caller
          type: pattern.type,
          marketFactor: article.title.substring(0, 80),
          internalImpact: pattern.impact,
          confidence: 65,
          direction,
          description: `Market news: "${article.title}". Potential business impact: ${pattern.impact}`,
        };
      }
    }

    return null;
  }

  /**
   * Analyze price trends for business implications
   */
  private static analyzePriceTrends(
    prices: PricePoint[]
  ): Correlation[] {
    const correlations: Correlation[] = [];

    if (prices.length < 2) return correlations;

    // Calculate trend
    const recent = prices.slice(0, 5); // Last 5 days
    const older = prices.slice(5, 20); // Days 5-20

    if (recent.length > 0 && older.length > 0) {
      const recentAvg = recent.reduce((sum, p) => sum + p.close, 0) / recent.length;
      const olderAvg = older.reduce((sum, p) => sum + p.close, 0) / older.length;
      const priceChange = ((recentAvg - olderAvg) / olderAvg) * 100;

      if (Math.abs(priceChange) > 2) {
        const direction = priceChange > 0 ? 'positive' : 'negative';
        const impact =
          priceChange > 0
            ? 'Company valuation increasing - positive market sentiment'
            : 'Company valuation decreasing - negative market sentiment';

        correlations.push({
          id: '', // Will be assigned by caller
          type: 'revenue',
          marketFactor: `Stock price ${priceChange > 0 ? 'up' : 'down'} ${Math.abs(priceChange).toFixed(2)}%`,
          internalImpact: impact,
          confidence: 70,
          direction: direction as 'positive' | 'negative',
          description: `Recent price change of ${priceChange.toFixed(2)}% may indicate ${impact}`,
        });
      }
    }

    return correlations;
  }

  /**
   * Analyze uploaded sales snapshot for market/business implications
   */
  private static analyzeSalesSnapshot(salesData: SalesDataSnapshot): Correlation | null {
    const deliveryPressure = Number(salesData.deliveryCostPercentage || 0);
    const trend = salesData.costTrend;
    const urgencyText = salesData.urgencyIndicators.join(' ').toLowerCase();

    if (trend === 'stable' && deliveryPressure < 8 && !urgencyText) {
      return null;
    }

    const negative = trend === 'increasing' || deliveryPressure >= 8 || urgencyText.includes('up');
    const positive = trend === 'decreasing' || deliveryPressure < 6;

    const direction: 'positive' | 'negative' | 'neutral' = negative
      ? 'negative'
      : positive
        ? 'positive'
        : 'neutral';

    return {
      id: '',
      type: 'cost',
      marketFactor: `Uploaded sales dataset (${salesData.period})`,
      internalImpact: `Total sales $${salesData.totalSales.toLocaleString('en-US')}, delivery cost ${deliveryPressure.toFixed(1)}%, trend ${trend}`,
      confidence: Math.min(90, Math.max(60, Math.round(70 + Math.abs(deliveryPressure - 8)))),
      direction,
      description: `Uploaded dataset shows ${trend} cost pressure and ${deliveryPressure.toFixed(1)}% delivery cost ratio. ${salesData.urgencyIndicators[0] || ''}`.trim(),
    };
  }

  /**
   * Generate recommendations from correlations
   */
  private static generateRecommendations(correlations: Correlation[]): Recommendation[] {
    const recommendations: Recommendation[] = [];
    let recId = 0;

    // Group correlations by type
    const byType = correlations.reduce(
      (acc, c) => {
        if (!acc[c.type]) acc[c.type] = [];
        acc[c.type].push(c);
        return acc;
      },
      {} as Record<string, Correlation[]>
    );

    // Generate recommendations per type
    for (const [type, corrs] of Object.entries(byType)) {
      const negativeCount = corrs.filter((c) => c.direction === 'negative').length;

      if (negativeCount > 0) {
        if (type === 'cost') {
          recommendations.push({
            id: `rec-${++recId}`,
            title: 'Optimize Cost Management',
            description:
              'Multiple cost pressures detected. Review vendors and operational efficiency.',
            actionItems: [
              'Schedule vendor negotiations',
              'Review procurement processes',
              'Analyze cost-saving opportunities',
              'Consider alternative suppliers',
            ],
            estimatedImpact: `Potential ${Math.min(negativeCount * 5, 15)}% cost reduction`,
            priority: negativeCount > 2 ? 'high' : 'medium',
            relatedCorrelations: corrs.map((c) => c.id),
          });
        } else if (type === 'supply') {
          recommendations.push({
            id: `rec-${++recId}`,
            title: 'Strengthen Supply Chain Resilience',
            description: 'Supply chain risks identified. Diversify sources and build redundancy.',
            actionItems: [
              'Identify alternative suppliers',
              'Increase inventory buffers',
              'Establish backup logistics routes',
              'Improve supplier communication',
            ],
            estimatedImpact: 'Reduce operational disruption risk',
            priority: 'high',
            relatedCorrelations: corrs.map((c) => c.id),
          });
        } else if (type === 'demand') {
          recommendations.push({
            id: `rec-${++recId}`,
            title: 'Adjust Sales & Marketing Strategy',
            description: 'Market demand shifting. Realign product focus and marketing efforts.',
            actionItems: [
              'Update sales forecasts',
              'Review product positioning',
              'Adjust marketing spend allocation',
              'Consider product development priorities',
            ],
            estimatedImpact: 'Better market alignment and revenue optimization',
            priority: 'medium',
            relatedCorrelations: corrs.map((c) => c.id),
          });
        }
      }
    }

    return recommendations;
  }

  /**
   * Generate auto tasks from correlations and recommendations
   */
  private static generateAutoTasks(
    correlations: Correlation[]
  ): AutoTask[] {
    const tasks: AutoTask[] = [];
    let taskId = 0;

    // Create tasks from high-confidence, negative correlations
    const urgentCorrs = correlations.filter((c) => c.confidence > 60 && c.direction === 'negative');

    urgentCorrs.forEach((corr) => {
      if (corr.type === 'cost' && corr.marketFactor.includes('Fuel')) {
        tasks.push({
          id: `task-${++taskId}`,
          title: 'Audit Logistics Providers',
          description: `Market news indicates ${corr.marketFactor}. Review logistics costs and efficiency.`,
          category: 'audit',
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
          assigneeSuggestion: 'Operations Manager',
          estimatedEffort: 'medium',
          linkedCorrelations: [corr.id],
        });
      }

      if (
        corr.type === 'supply' ||
        (corr.description.toLowerCase().includes('supply') && corr.direction === 'negative')
      ) {
        tasks.push({
          id: `task-${++taskId}`,
          title: 'Review Supply Chain Strategy',
          description: `Potential supply disruption detected. Review sourcing strategy and supplier relationships.`,
          category: 'strategic',
          dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
          assigneeSuggestion: 'Supply Chain Manager',
          estimatedEffort: 'large',
          linkedCorrelations: [corr.id],
        });
      }
    });

    // Create monitoring tasks for significant market movements
    const significantMovements = correlations.filter((c) => c.confidence > 70);
    if (significantMovements.length > 0 && tasks.find((t) => t.category === 'monitoring') === undefined) {
      tasks.push({
        id: `task-${++taskId}`,
        title: 'Monitor Market Developments',
        description: `Significant market developments detected (${significantMovements.length} items). Continue monitoring and adjust strategies as needed.`,
        category: 'monitoring',
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        assigneeSuggestion: 'Business Analyst',
        estimatedEffort: 'small',
        linkedCorrelations: significantMovements.map((c) => c.id),
      });
    }

    return tasks;
  }

  /**
   * Assess overall risk level
   */
  private static assessRiskLevel(correlations: Correlation[]): 'low' | 'medium' | 'high' | 'critical' {
    if (correlations.length === 0) return 'low';

    const negativeCount = correlations.filter((c) => c.direction === 'negative').length;
    const avgConfidence =
      correlations.reduce((sum, c) => sum + c.confidence, 0) / correlations.length;

    const riskScore = (negativeCount / correlations.length) * (avgConfidence / 100);

    if (riskScore > 0.6) return 'critical';
    if (riskScore > 0.4) return 'high';
    if (riskScore > 0.2) return 'medium';
    return 'low';
  }

  /**
   * Generate human-readable summary
   */
  private static generateSummary(
    correlations: Correlation[],
    recommendations: Recommendation[],
    riskLevel: string
  ): string {
    const negCount = correlations.filter((c) => c.direction === 'negative').length;
    const posCount = correlations.filter((c) => c.direction === 'positive').length;

    return `Analysis Summary: Found ${correlations.length} correlations between market trends and business data. 
${negCount} negative, ${posCount} positive trends. 
Risk Level: ${riskLevel}. 
${recommendations.length} strategic recommendations generated.
${
      recommendations.length > 0
        ? `Key recommendation: ${recommendations[0].title}`
        : 'Continue monitoring market developments.'
    }`;
  }
}
